### PR TITLE
Implementing node-portfinder

### PR DESCRIPTION
**Pull request by kevinchevallier**
Implemented [node-portfinder](https://github.com/indexzero/node-portfinder) to dynamically get a free port.

### CODE REVIEW

**Comment by caiovaccaro** [comment]
Have you added it to dependencies?

**Comment by kevinchevallier** [comment]
No hadn't, my bad. Corrected it in a new commit.

**Comment by caiovaccaro** [comment]
Can you version bump this to 2.0.6?

Update the Readme, package.json, etc, still on this PR.

**Comment by kevinchevallier** [comment]
Updated readme, package.json and the git tag version. Hope i didnt miss one.

**Comment by caiovaccaro** [comment]
I'm merging now, please make this PR again to the develop branch.

**Comment by Nipher** [comment]
Develop updated :smiley: 
Nice work @kevinchevallier

**Comment by kevinchevallier** [comment]
Just updated the readme. Should i create a new PR or can you still merge?

**Comment by caiovaccaro** [comment]
New PR.

**Comment by caiovaccaro** [comment]
And please @Nipher do git push --tags.

**Pull request merged**
