### PR TITLE
Script for dependecies

### PR DESCRIPTION
**Pull request by Ionut-Milas**
Saw that a lot of guys got stuck at 94% and having the info dispersed it's not so great, so I've created an npm script that will take care of the dependencies.

### CODE REVIEW

**Comment by Nipher** [comment]
Hey @GraphicDesk, thank you for this PR.

Maybe we could install all global dependencies as local dependencies, and run them directly from `node_modules`, instead of creating an npm script to install global dependencies.

Like this: `./node_modules/.bin/harp compile` maybe.

@caiovaccaro, @GraphicDesk  what do you think?
Seems like that "stuck 94%" problem on #72 and #75 is caused by harp's absence.

**Comment by GraphicDesk** [comment]
@Nipher Sounds good from my point of view. However I've got some issues with harp compile.
I'm fond of having tasks for installing, and tasks for compiling, etc... We could remove the "-g" from the script as well ...

**Comment by caiovaccaro** [comment]
Yep. Running everything locally is ideal. Can you do that @Ionut-Milas ?

**Comment by caiovaccaro** [comment]
Merged onto develop.

**Pull request closed without merging**
